'use client'
import React from 'react';
import Navbar from '@/components/navbar/Navbar';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Footer from '@/components/navbar/footer/Footer';
import{ usePathname } from 'next/navigation';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname()

  // Check if the current route is the login or signup page
  const isLoginPage = pathname === '/login';
  const isSignupPage = pathname === '/signup';

  // Hide the navbar in the login and signup pages
  const hideNavbar = isLoginPage || isSignupPage;

  return (
    <html lang="en">
      <body className={inter.className}>
        {!hideNavbar && <Navbar />}
        {children}
        <Footer />
      </body>
    </html>
  );
}
