'use client'
import React from 'react';
import Navbar from '@/components/navbar/Navbar';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Footer from '@/components/navbar/footer/Footer';
import{ usePathname } from 'next/navigation';
import AuthProvider  from '@/components/isAuth/authContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname()

  // Check if the current route is the login or signup page
  const isLoginPage = pathname === '/login';
  const isSignupPage = pathname === '/signup';

  // Hide the navbar in the login and signup pages
  const hideNavbar = isLoginPage || isSignupPage;



  return (
    <AuthProvider >
    <html lang="en">
<head>
<link href="https://www.w3schools.com/w3css/4/w3.css"
        rel="stylesheet"/>
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossOrigin="anonymous"/>

</head>
     
      <body className={inter.className}>
      
        {!hideNavbar && <Navbar />}
        {children}
        <Footer />
      </body>
    </html>
    </AuthProvider>
  );

};
